<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

  <title><![CDATA[Category: 3D | Bohumír Zámečník]]></title>
  <link href="http://bohumirzamecnik.cz/blog/categories/3d/atom.xml" rel="self"/>
  <link href="http://bohumirzamecnik.cz/"/>
  <updated>2016-09-09T17:35:05+02:00</updated>
  <id>http://bohumirzamecnik.cz/</id>
  <author>
    <name><![CDATA[Bohumír Zámečník]]></name>
    
  </author>
  <generator uri="http://octopress.org/">Octopress</generator>

  
  <entry>
    <title type="html"><![CDATA[How to Make STL With SVG Logo and Text in OpenSCAD]]></title>
    <link href="http://bohumirzamecnik.cz/blog/2016/how-to-make-stl-with-svg-logo-and-text-in-openscad/"/>
    <updated>2016-05-01T18:02:51+02:00</updated>
    <id>http://bohumirzamecnik.cz/blog/2016/how-to-make-stl-with-svg-logo-and-text-in-openscad</id>
    <content type="html"><![CDATA[<p><img src="/assets/blog/categories/3d/example_reel.png" width="300" align="right">
We&rsquo;ll see how to create an STL model of a stylized filament reel with a logo from SVG and some text without clicking the mouse. Yes we&rsquo;ll write it procedurally in OpenSCAD, use templating and automate the whole thing. We&rsquo;ll see how OpenSCAD is a really natural tool for programmer and it very easy to start playing with and get impressive results.</p>

<div style="clear:both"></div>




<!--more-->


<p>Our today&rsquo;s goal is to prepare around 20 3D-printed things representing filament reels, each with a inset logo and a short name of the material. This little weekend project was done for <a href="http://www.svet-3d-tisku.cz/">Svět 3D Tisku</a> (3D Print World), a local 3D print company ran by my parents, for <a href="http://3dexpo.cz/">3D Expo Prague 2016</a>. Imagine a big poster to present a collection of filament materials and for each there&rsquo;s a nice small tangible artifact made of that material.</p>

<p><img src="/assets/blog/categories/3d/example_reel.png"></p>

<h2>OpenSCAD &ndash; Constructive Solid Geometry</h2>

<p>Since I like programming more than GUI modeling tools and mouse clicking, I decided to try <a href="http://www.openscad.org/">OpenSCAD</a>. It allows to make 3D models using the <a href="https://en.wikipedia.org/wiki/Constructive_solid_geometry">Constructive Solid Geometry</a> (CSG) and <a href="https://en.wikipedia.org/wiki/Procedural_modeling">procedural modeling</a> paradigms. Ie. we the model from primitive parts (cube, 2D polygon, linear extrusion), by applying transformations (traslate, scale, rotate) and set operations (union, intersection, difference). The model is described by a custom programming language. This is a different to the triangle mesh representation where only the border, not the solid itself is described.</p>

<p>For programmers the whole concept is much more intuitive and natural, eg. when compared to Blender with its overly complex UI with hard learning curve.</p>

<p>After I finished this project it felt vary natual and familiar. Then I realized I&rsquo;ve already done something similar a few years ago in open-source <a href="https://renderman.pixar.com/">RenderMan</a> implementation <a href="http://www.renderpixie.com/gallery.html">Pixie</a> for the university projected on the <a href="http://cgg.mff.cuni.cz/~wilkie/Website/NPGR027.html">Shading Languages</a> course.</p>

<p>Please refer to the <a href="https://en.wikibooks.org/wiki/OpenSCAD_User_Manual">OpenSCAD User Manual</a> and the example models for the basics of OpenSCAD. Basically you write your code in one pane and see the model in the other. Useful keyboard shortcuts and commands.</p>

<ul>
<li><code>F5</code> &ndash; refresh the preview</li>
<li><code>F6</code> &ndash; render the model (do this before saving to STL)</li>
<li><code>File</code> &ndash;> <code>Export</code> &ndash;> <code>Export to STL</code></li>
<li><code>CMD-D</code> &ndash; comment</li>
<li><code>CMD-SHIFT-D</code> &ndash; uncomment</li>
</ul>


<p>Comments are C-like, ie. <code>// ...</code> and <code>/* ... */</code></p>

<p><img src="/assets/blog/categories/3d/openscad.png"></p>

<h2>Creating a model &ndash; step by step</h2>

<p>We would like to get a shape that roughly looks like a <a href="https://www.google.com/search?q=filament+reel">filament reel</a> but is not too complex. On top of it we would like to put a logo and some abbreviation of the material name. We can model it in the dimensions of a real reel and than scale it to the final model size.</p>

<p>Real world example (colorFabb COPPERFILL Ø 2,85 m / 4m):</p>

<p><a href="http://eshop.svet-3d-tisku.cz/3d-tiskovy-material/tiskova-struna-medena-3d-filament-copperfill--2-85-mm-10m/"><img src="/assets/blog/categories/3d/copperfill_reel.jpg"></a></p>

<p>There are example snippets of code throughout the article. The complete source code is available in a git repo linked at the end of the article. You can clone it and play with it yourself. It&rsquo;s fully working.</p>

<h2>Basic reel shape</h2>

<p>The basic shape is a cylinder, ie. an extruded circle. The <code>$fn</code> argument makes the circle smoother &ndash; the circle is represented as a regular polygon and <code>$fn</code> specifies the number of its edges. Eg. cylinder of 190mm diameter, 20 mm high to represent the inner reel:</p>

<p>```
linear_extrude(height=20) {</p>

<pre><code>circle(d=190, $fn=200);
</code></pre>

<p>}
```</p>

<p>In the final model it is shown in red.</p>

<p><img src="/assets/blog/categories/3d/inner_cylinder.png"></p>

<h3>Functions, set operations</h3>

<p>Let&rsquo;s add two outer reels and a hole. As I said the model is really stylized and so the proportions do not match excatly a real-world reel. We can transform the primitives and operate on them with set operations. We can also extract constants to variables and refactor parts into functions (modules) which also can be parameterized.</p>

<p>```
outer_diameter = 200;
reel_diameter = 190;
hole_diameter = 55;
width = 20;
outer_reel_width = 5;
rim_height = 2;</p>

<p>module inner_reel() {</p>

<pre><code># without a semicolon this transformations affects the next statement
translate([0, 0, -width/2])
linear_extrude(height=width-rim_height*2) {
    circle(d=reel_diameter, $fn=200);
}
</code></pre>

<p>}
module plain_outer_reel() {</p>

<pre><code>linear_extrude(height=outer_reel_width) {
    circle(d=outer_diameter, $fn=400);
}
</code></pre>

<p>}</p>

<p>module hole() {</p>

<pre><code>translate([0, 0, -width])
linear_extrude(height=2*width) {
    circle(d=hole_diameter, $fn=200);
}
</code></pre>

<p>}</p>

<h1>CSG set operations</h1>

<p>difference() {
  union() {</p>

<pre><code>inner_reel();
plain_outer_reel();
</code></pre>

<p>  }
  hole();
}
```</p>

<p><img src="/assets/blog/categories/3d/outer_cylinders.png"></p>

<h3>Tip &ndash; visual debugging</h3>

<p>A very useful way to ensure you are making the correct operations is visual debugging. Just add a <code>#</code> character before any part and it is displayed in transparent red. This way you can be sure what you are intersecting and diffing.</p>

<p><img src="/assets/blog/categories/3d/hole.png"></p>

<h3>Beveled side + ribs</h3>

<p>Let&rsquo;s add some rim by beveling the side and add some ribs just to make it look a bit more like a real reel.</p>

<p>```
module rib() {</p>

<pre><code>translate([hole_diameter/2 + rib_margin, -rim_height/2, outer_reel_width - rim_height])
cube([outer_diameter/2 - (hole_diameter/2 + 2*rib_margin), rim_height, rim_height]);
</code></pre>

<p>}</p>

<p>module ribs() {</p>

<pre><code># this is the power of procedural models vs. clicking!
for (angle=[0, 60, 120, 180, 240, 300]) {
    rotate(angle) rib();
}
</code></pre>

<p>}</p>

<p>module outer_reel() {</p>

<pre><code>union() {
    ribs();
    difference() {
        plain_outer_reel();
        color("gray")
        translate([0, 0, outer_reel_width - 2])
        linear_extrude(height=2+1) {
            circle(d=outer_diameter - 5, $fn=400);
        }
    }
}
</code></pre>

<p>}</p>

<p>module plain_reel() {</p>

<pre><code>inner_reel();
translate([0, 0, width / 2 - outer_reel_width])
// upper reel
outer_reel();
// lower reel
translate([0, 0, -width / 2])
rotate([180, 0, 0])
plain_outer_reel();
</code></pre>

<p>}
```</p>

<p><img src="/assets/blog/categories/3d/bevel_and_ribs.png"></p>

<h3>Conic supports</h3>

<p>Originally I though it would be nice to make some thin flat outer circular parts of the reel (that holds the filament from sides). When we printed it I realized it needs supports, otherwise the printer just extrudes into air. To avoid using supports and save some priting time we modified the models to make some small supports directly in the model. Just add some conic sections that smoothly interpolate betweeen the inner and outer diameter.</p>

<p>Fortunately OpenSCAD provides this functionality right in the <code>linear_extrude</code> primitive, just and the <code>scale</code> parameter:</p>

<p>```
module conic_support() {</p>

<pre><code>linear_extrude(height=4, scale=1.05) {
    circle(d=reel_diameter, $fn=200);
}
</code></pre>

<p>}</p>

<p>module inner_reel() {</p>

<pre><code>// inner cylinder
translate([0, 0, -width/2])
linear_extrude(height=width-rim_height*2) {
    circle(d=reel_diameter, $fn=200);
}

// upper conic support
translate([0, 0, 1.1])
conic_support();

// lower conic support    
translate([0, 0, -6.1])
rotate([180, 0, 0])
conic_support();
</code></pre>

<p>}
```</p>

<p>It worked like charm and the models was printed well.</p>

<p><img src="/assets/blog/categories/3d/conic_supports.png"></p>

<h2>Logo &ndash; from SVG</h2>

<p>Now when we have a nice reel let&rsquo;s enhance it by adding our logo. Our logo is some vector graphics, so a <a href="https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/DXF_Extrusion">DXF extrusion</a> is an option.</p>

<p>I&rsquo;ve extracted just a part of the logo from an AI (Illustrator) file and saved it as SVG. OpenSCAD can only open 2D vector files from DXF (Autocad), not SVG, so we have to first convert the SVG to DXF.</p>

<p>I&rsquo;ve tried a few options and only this Inkscape plugin for export the DXF worked well: <a href="https://github.com/brad/Inkscape-OpenSCAD-DXF-Export">Inkscape-OpenSCAD-DXF-Export</a>. Just download the repo and copy the dir and <code>*.inx</code> to <code>~/.config/inkscape/extensions</code> (on Mac) and than start Inkscape. Then just open the SVG and <code>File -&gt; Save copy -&gt; OpenSCAD DXF Output</code>.</p>

<p>Then in OpenSCAD we import it into a 2D object:</p>

<p><code>
import('logo.dxf');
</code></p>

<p>In order to use it in CSG operations we have to extrude it:</p>

<p>```
module logo(height) {</p>

<pre><code>linear_extrude(height = height) {
    scale(0.15)
    import(logo_file);
}
</code></pre>

<p>}
```</p>

<p>In case nothing appears, make sure you select the default layer or the proper one. Look for <code>AcDbLayerTableRecord</code> in the DXF file. I once copied an example from the docs and it selected some other layer and I though the DXF file is not compatible. Also the model from DXF might have to be translated to the original of coordinates.</p>

<p>Let&rsquo;s inscribe the logo in the upper reel part:</p>

<p>```
module logo_inscription() {</p>

<pre><code>translate([0, -0.7 * outer_diameter/2, width/2 - rim_height - inscription_depth])
translate([-32.5,-22,0])
logo(1.1 * inscription_depth); // + epsilon
</code></pre>

<p>}</p>

<p>difference() {</p>

<pre><code>plain_reel();
logo_inscription();
</code></pre>

<p>}
```</p>

<p><img src="/assets/blog/categories/3d/logo.png"></p>

<p>The logo itself is a bit thicker and if we make it as thick as is lowered we may get into numerical problems. The solution is easy, just make it overlap a bit (by a small epsilon). If you&rsquo;ve ever came across computational geometry or numerical programming this should have been deeply rooted in your blood :). Otherwide, you&rsquo;ve just learned. Tip for reading: <a href="http://gamedevs.org/uploads/numerical-robustness-geometric-calculations.pdf">Numerical Robustness
(for Geometric Calculations)</a>.</p>

<p><img src="/assets/blog/categories/3d/epsilon.png"></p>

<h2>Text</h2>

<p>Then we&rsquo;d like to add some short description text inscriped in the the upper side similarly as the logo. OpenSCAD directly supports 2D text primitives which can be then extruded. That&rsquo;s exactly what we need.</p>

<p><code>
linear_extrude(height=1) {
  text("ABS");
}
</code></p>

<p>We can set the text size, alignment and font to customize the text for aesthetics and legibility:</p>

<p><code>
font = "Liberation Sans:style=Bold";
text("ABS", 20, halign="center", font=font);
</code></p>

<p>We have texts of various length like &ldquo;ABS&rdquo;, &ldquo;BRASS&rdquo;, &ldquo;PETG ESD&rdquo; so we need to customize the font size and and Y position individually for a good git.</p>

<h3>Multiline text</h3>

<p>In order to use the space well without compromizing legibility we can split the text into multiple lines (in this case usually two). Since OpenSCAD&rsquo;s <code>text()</code> only supports a single line, we need to make more translated <code>text()</code> objects and union them. We&rsquo;re not the first to come across this problem and fortunately <a href="https://www.reddit.com/r/openscad/comments/3jwobs/line_feed_in_openscad_text/">other people managed to get a working solution</a>. So we&rsquo;ll use a snippet by user <em>iggy_koopa</em>.</p>

<p>```
module multiline_text(lines, size){
  // <a href="https://www.reddit.com/r/openscad/comments/3jwobs/line_feed_in_openscad_text/">https://www.reddit.com/r/openscad/comments/3jwobs/line_feed_in_openscad_text/</a></p>

<pre><code>union(){
    for (i = [0 : len(lines)-1]) {
        translate([0 , -i * (size + 2), 0])
        text(lines[i], size, halign="center", font=font);
    }
}
</code></pre>

<p>}</p>

<p>module description(desc, size, y_pos) {</p>

<pre><code>translate([0, y_pos * outer_diameter/2, width/2 - rim_height - inscription_depth])
// epsilon trick
linear_extrude(height=1.1 * inscription_depth) {
    multiline_text(desc, size);
}
</code></pre>

<p>}</p>

<p>description([&ldquo;ABS&rdquo;, &ldquo;ESD&rdquo;], 17, 0.7);
```</p>

<p>The same epsilon trick as with the logo still holds.</p>

<p><img src="/assets/blog/categories/3d/text.png"></p>

<h2>Scaling the whole model</h2>

<p>The basic units in OpenSCAD are millimeters. Since we used dimensions of a real reel (with 20 cm diameter) but want our models smaller (eg. 8 cm), we can just scale the shole model.</p>

<p>```
module reel(desc, desc_size, desc_y_pos) {</p>

<pre><code>scale(8 / 20)
difference() {
    difference() {
        plain_reel();
        union() {
            logo_inscription();
            description(desc, desc_size, desc_y_pos);
        }
    }
    hole();
}
</code></pre>

<p>}
```</p>

<h2>Exporting to STL</h2>

<p>Now we have single reel model and it&rsquo;s time to export an STL. In the UI it is quite simple:</p>

<ul>
<li><code>F6</code> &ndash; render the model</li>
<li><em>File</em> &ndash;> <em>Export</em> &ndash;> <em>Export to STL</em></li>
</ul>


<p>In order to automate the things it would be nice to call <a href="https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_OpenSCAD_in_a_command_line_environment">OpenSCAD via command line</a>. Fortunately, it supports it!</p>

<p>On Mac the binary is buried in <code>/Applications</code>, so to use it a little bit more comfortable we can link it to our <code>~/bin</code>. This is optional.</p>

<p>```</p>

<h1>make sure you have ~/bin in your PATH</h1>

<p>$ mkdir -p ~/bin
$ export PATH=PATH:~/bin
$ ln -s /Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD ~/bin/openscad
```</p>

<p>Then we can produce STL from an SCAD file this way:</p>

<p><code>
$ openscad -o foo.stl -D 'quality="production"' foo.scad
</code></p>

<p>It is quite slow. This model took about 1:15 min.</p>

<h2>Exporting to PNG</h2>

<p>Similarly we can export a thumbnail to PNG:</p>

<p><code>
$ openscad -o foo.png foo.scad
</code></p>

<p>Also we can set the camera position and orientation:</p>

<p><code>
$ openscad -o foo.png foo.scad --camera=0,0,220,0,0,0
</code></p>

<p>Refer to the docs for details.</p>

<p><img src="/assets/blog/categories/3d/reel_00_ABS_ESD.png"></p>

<h2>Parametric models</h2>

<p>It is nice that we were able to create one model but we want a models for each of ~ 20 materials. Well, we could copy a model, change something and save as another file. But such approach get too cumbersome when we want to change something and propagate the change into all the instnaces. Better, we can try to automate the whole process.</p>

<p>So we can make a parameterized model with variable text, font size and text position and then use it to make multiple instances. We want a separate STL for each model, so we have to create mulitple separate SCAD files.</p>

<p>An easy approach is to use eg. Python as the templating engine, store the parameters in a table (a CSV file) and generate multiple SCAD files. Then for each SCAD file we&rsquo;ll generate the STL and PNG thumbnail.</p>

<p>We store the parameterized model in the <code>reel.scad</code> file and provide a function:</p>

<p><code>
module reel(desc, desc_size, desc_y_pos) {
  // ...
}
</code></p>

<p>Then we can include this file and call the <code>reel()</code> function to instantiate the model with given parameters and store it to other file:</p>

<p><code>
use &lt;reel.scad&gt;;
reel(["ABS", "ESD"], 18, 0.7);
</code></p>

<h2>Automating the whole thing</h2>

<h3>Python template generator</h3>

<p>We store the definitions into a CSV file <code>reel_texts.csv</code>. The text column is split on whitespace into multiple lines. The size is text size in mm, the y_pos is the relative Y position.</p>

<p><code>
text,size,y_pos
ABS ESD,18,0.7
PETG ESD,18,0.7
ABS,20,0.6
[...]
</code></p>

<p>To read the CSV we use <code>pandas</code>. Then we transform each row into a SCAD source code and store it into a file.</p>

<p>```
import os
import pandas as pd</p>

<p>df = pd.read_csv(&lsquo;reel_texts.csv&rsquo;, dtype=str)</p>

<p>template = &ldquo;&rdquo;&ldquo;use &lt;../reel.scad>;
reel([%s], %s, %s);
&rdquo;&ldquo;&rdquo;</p>

<p>dir_name = &lsquo;reels_scad&rsquo;
os.makedirs(dir_name, exist_ok=True)
for index, row in df.iterrows():</p>

<pre><code>normalized_text = row['text'].replace(' ', '_').replace('/', '')
file_name = '%s/reel_%02d_%s.scad' % (dir_name, index, normalized_text)
with open(file_name, 'w') as f:
    text = ', '.join(['"%s"' % t for t in row['text'].split(' ')])
    f.write(template % (text, row['size'], row['y_pos']))
</code></pre>

<p>```</p>

<h3>Converting to STL in batch</h3>

<p>Let&rsquo;s convert all the generated SCAD files to STL files and store them to another directory. For ~ 20 files it took about half an hour. Right now I haven&rsquo;t tried to optimize it.</p>

<p>```</p>

<h1>!/bin/bash</h1>

<h1>Convert all reels from SCAD to STL</h1>

<p>STL_DIR=stl
mkdir -p $STL_DIR
for SCAD_FILE in reels_scad/*.scad; do
  STL_FILE=$STL_DIR/$(basename $SCAD_FILE .scad).stl
  time openscad -o $STL_FILE -D &lsquo;quality=&ldquo;production&rdquo;&rsquo; $SCAD_FILE
done
```</p>

<h3>Converting to PNG in batch</h3>

<p>We can do similar thing to obtain PNG thumbnails:</p>

<p><code>
PNG_DIR=png
mkdir -p $PNG_DIR
for SCAD_FILE in reels_scad/*.scad; do
  PNG_FILE=$PNG_DIR/$(basename $SCAD_FILE .scad).png
  openscad -o $PNG_FILE $SCAD_FILE --camera=0,0,220,0,0,0
done
</code></p>

<h3>Bonus &ndash; array of thumbnails</h3>

<p>It might be nice to see all the thumbnails in a single image. Python, numpy and matplotlib can save us and to the job in a few lines of code.</p>

<p><img src="/assets/blog/categories/3d/thumbnails.png"></p>

<p>```
&ldquo;&rdquo;&ldquo;
Makes a single thumbnail image from a set of individual PNGs.
Order the images into a 2D matrix, so that it&rsquo;s nicely viewable.
&rdquo;&ldquo;&rdquo;</p>

<p>import matplotlib.pyplot as plt
import numpy as np
import glob</p>

<p>image_files = glob.glob(&lsquo;png/*.png&rsquo;)</p>

<p>w, h, channels = 512, 512, 3
rows, cols = 4, 5</p>

<h1>let&rsquo;s make a matrix 4x5, ie. select a nicely divisible subset</h1>

<p>image_files = image_files[:rows * cols]
images = [read_image(f) for f in image_files]</p>

<h1>make a single big matrix of images</h1>

<h1>(20, 512, 512, 3) &ndash;></h1>

<p>images = np.vstack(images).reshape(rows, cols, w, h, channels)</p>

<h1>(4, 5, 512, 512, 3) &ndash;> (4, 512, 5, 512, 3) &ndash;> (4 * 512, 5 * 512, 3)</h1>

<p>big_image = images.swapaxes(1, 2).reshape(rows * w, cols * h, channels)</p>

<p>plt.imsave(&lsquo;thumbnails.png&rsquo;, big_image)
```</p>

<h2>The code &ndash; git repository</h2>

<p>That&rsquo;s it!</p>

<p>The complete code, including the scripts and graphics is available in a git repository. The license code the code (except for the logo) it MIT open-source, so feel free to use it.</p>

<ul>
<li><a href="https://github.com/bzamecnik/s3dt-models/">https://github.com/bzamecnik/s3dt-models/</a></li>
</ul>


<h2>About the company</h2>

<p><img src="http://www.svet-3d-tisku.cz/img/svet-3d-tisku-logo.png" alt="" /></p>

<p><a href="http://www.svet-3d-tisku.cz/">Svět 3D tisku</a> (3D Print World) is a Czech boutique e-shop and store providing broad range of fillaments, 3D printers and custom 3D print services for Central European customers (local companies, schools, hobbyists). The company is ran by by mum and dad and I&rsquo;m trying to help them if time permits.</p>

<p>If you are in Prage around 10.-13. May 2016 feel free to visit our stand at <a href="http://3dexpo.cz/">3D Expo Prague 2016</a> (<a href="http://3dexpo.cz/exhibitors/svet-3d-tisku/">details</a>) and see the printed &ldquo;reels&rdquo; live :).</p>

<h2>Conclusion</h2>

<p>In this small weekend project we&rsquo;ve learned the basics of OpenSCAD and were able to create some nice small but not completely trivial model. We&rsquo;ve seem how to use a hierarchy of parameterized models, how to use text, import vector graphics logo from SVG and use it as an inscription. In order to avoid repetitive work we tried to automate all the steps from generating SCAD code, STL and PNG file up to making a summary table of thumbnails.</p>

<p>I hope this article has shown you that it is very easy to start with OpenSCAD (at least for programmers) and inspired you to make your own projects. If you have any questions, you can search the docs or drop some comment here. Thanks and enjoy!</p>
]]></content>
  </entry>
  
</feed>
